mod day01;
mod day02;
mod day03;
mod day04;
mod day05;
mod day06;
mod day07;
mod day08;
mod day09;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day17;
mod day18;
mod day19;
mod day20;
mod day21;
mod day22;
mod day23;
mod day24;

fn main() {
    if let Err(_) = day01::run() {()};
    if let Err(_) = day02::run() {()};
    if let Err(_) = day03::run() {()};
    if let Err(_) = day04::run() {()};
    if let Err(_) = day05::run() {()};
    if let Err(_) = day06::run() {()};
    if let Err(_) = day07::run() {()};
    if let Err(_) = day08::run() {()};
    if let Err(_) = day09::run() {()};
    if let Err(_) = day10::run() {()};
    if let Err(_) = day11::run() {()};
    if let Err(_) = day12::run() {()};
    if let Err(_) = day13::run() {()};
    if let Err(_) = day14::run() {()};
    if let Err(_) = day15::run() {()};
    if let Err(_) = day16::run() {()};
    if let Err(_) = day17::run() {()};
    if let Err(_) = day18::run() {()};
    if let Err(_) = day19::run() {()};
    if let Err(_) = day20::run() {()};
    if let Err(_) = day21::run() {()};
    if let Err(_) = day22::run() {()};
    if let Err(_) = day23::run() {()};
    if let Err(_) = day24::run() {()};
}

